name: hello world

on: [push]

jobs:
  hola:
    runs-on: ubuntu-latest
    steps:
      - name: create hello file
        run: echo hola mundo.txt
      - name: print hello-world on file
        run: echo "hola mundo" > hola.txt
      - name: read hello-world file
        run: more hello-wrld.txt
  atual-directory:
    runs-on: ubuntu-latest
    steps:
      - name: print current directory
        run: pwd
