name: hello world

on: [push]

jobs:
  hola:
    runs-on: ubuntu-latest
    steps:
      - name: create hello file
        run: echo hola-mundo.txt
      - name: print hello world on file
        run: echo "hola mundo" > hola-mundo.txt
      - name: read hola-mundo file
        run: more hola-mundo.txt
  atual-directory:
    runs-on: ubuntu-latest
    steps:
      - name: print current directory
        run: pwd
